gemfile: .overcommit_gems.rb
verify_signatures: false

CommitMsg:
  TextWidth:
    enabled: false

PreCommit:
  RuboCop:
    command: bin/rubocop-daemon-wrapper
    enabled: true
    flags:
      - --disable-pending-cops
      - --parallel
      - --config=config/rubocop_strict.yml
    on_warn: fail

  SlimLint:
    command: bin/slim-lint
    enabled: true
    on_warn: fail

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.slim' # Markdown blocks need 2 trailing spaces to insert <br>
      - '**/db/structure.sql'
