version: 2
jobs:
  build:
    working_directory: ~/lw-web
    docker:
      - image: circleci/ruby:2.6-buster-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: lifework
          RAILS_ENV: test
          NODE_ENV: development
      - image: circleci/postgres:12-alpine-ram
        environment:
          POSTGRES_USER: lifework
          POSTGRES_PASSWORD: ''

    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler -v=$(cat Gemfile.lock | tail -1 | tr -d " ")

      - run:
          name: Install PSQL
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client-common postgresql-client
          background: true

      - run:
          name: Log versions
          command: |
            ruby -v
            bundle -v
            node -v
            yarn -v
            chromedriver -v
            google-chrome --version
          background: true

      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-lifework-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-lifework-bundle-{{ arch }}-{{ .Branch }}-
            - v1-lifework-bundle-{{ arch }}-

      - run:
          name: Bundle Install
          command: bin/bundle install --path vendor/bundle --jobs 5 --retry 3 --without production development && bin/bundle clean

      - save_cache:
          name: Store bundle cache
          key: v1-lifework-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop
          command: bin/rubocop --parallel

      - run:
          name: Slim Lint
          command: bin/slim-lint app/views

      - restore_cache:
          name: Restore yarn cache
          keys:
            - v1-lifework-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-lifework-yarn-{{ .Branch }}-
            - v1-lifework-yarn-

      - run:
          name: Yarn Install
          command: yarn install --verbose

      - save_cache:
          name: Store yarn cache
          key: v1-lifework-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: ESLint & StyleLint
          command: yarn lint

      - restore_cache:
          name: Restore webpacker cache
          keys:
            - v1-lifework-webpacker-{{ .Branch }}-
            - v1-lifework-webpacker-

      - restore_cache:
          name: Restore compiled packs
          key: v1-lifework-packs-{{ checksum "tmp/cache/webpacker/last-compilation-digest-test" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            cp config/database.yml.example config/database.yml
            bin/rake db:setup --trace

      - run:
          name: Compile packs
          command: bin/rake webpacker:compile --trace

      - save_cache:
          name: Store webpacker cache
          key: v1-lifework-webpacker-{{ .Branch }}-{{ epoch }}
          paths:
            - tmp/cache/webpacker

      - save_cache:
          name: Store compiled packs
          key: v1-lifework-packs-{{ checksum "tmp/cache/webpacker/last-compilation-digest-test" }}
          paths:
            - public/packs-test

      - run:
          name: Ruby tests
          command: CODECOV_FLAG=ruby bin/rspec spec/ --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml

      - store_test_results:
          path: ~/test-results/rspec/

      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots

      - store_artifacts:
          path: log/test.log
          destination: test.log
