version: 2.1
orbs:
  browser-tools: circleci/browser-tools@volatile
jobs:
  build:
    working_directory: ~/lw-web
    docker:
      - image: cimg/ruby:2.7-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: lifework
          NODE_ENV: test
          RAILS_ENV: test
          PSQL_PAGER: ''
      - image: cimg/postgres:14.9
        environment:
          POSTGRES_USER: lifework
          POSTGRES_PASSWORD: ''
    resource_class: large

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - checkout

      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile && touch .yarn-finished
          background: true

      - run:
          name: Setup database deps
          command: |
            cp config/database.yml.example config/database.yml
          background: true

      - run:
          name: Install Bundler
          command: gem install bundler -v=$(cat Gemfile.lock | tail -1 | tr -d " ")

      - run:
          name: Log versions
          command: |
            lsb_release -d
            ruby -v
            bundle -v
            node -v
            yarn -v
            psql -V
            chromedriver -v
            google-chrome --version
          background: true

      - restore_cache:
          name: Restore bundle cache
          keys:
            - v1-lifework-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-lifework-bundle-{{ arch }}-{{ .Branch }}-
            - v1-lifework-bundle-{{ arch }}-

      - run:
          name: Bundle install
          command: |
            bin/bundle config set --local path 'vendor/bundle'
            bin/bundle config set --local without 'production development'
            bin/bundle install --jobs 5 --retry 3
            bin/bundle clean

      - save_cache:
          name: Store bundle cache
          key: v1-lifework-bundle-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop
          command: bin/rubocop --disable-pending-cops --parallel --config=config/rubocop_strict.yml

      - run:
          name: Slim Lint
          command: bin/slim-lint app/views

      - run:
          name: Wait for yarn install
          command: dockerize -wait file://$(pwd)/.yarn-finished -timeout 2m

      - run:
          name: ESLint & StyleLint
          command: yarn lint

      - restore_cache:
          name: Restore webpacker cache
          keys:
            - v3-lifework-webpacker-{{ .Branch }}-
            - v3-lifework-webpacker-

      - restore_cache:
          name: Restore compiled packs
          key: v3-lifework-packs-{{ checksum "tmp/cache/webpacker/last-compilation-digest-test" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rake db:setup --trace

      - run:
          name: Compile packs
          command: bin/rake webpacker:compile --trace

      - save_cache:
          name: Store webpacker cache
          key: v3-lifework-webpacker-{{ .Branch }}-{{ epoch }}
          paths:
            - tmp/cache/webpacker

      - save_cache:
          name: Store compiled packs
          key: v3-lifework-packs-{{ checksum "tmp/cache/webpacker/last-compilation-digest-test" }}
          paths:
            - public/packs-test

      - run:
          name: Ruby tests
          command: CODECOV_FLAG=ruby bin/rspec spec/ --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml

      - store_test_results:
          path: ~/test-results/rspec/

      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots

      - store_artifacts:
          path: log/test.log
          destination: test.log
