source 'https://rubygems.org'

ruby "~> #{`cat .ruby-version`.strip}"

gem 'rails', '~> 6.0.0'

gem 'aasm' # Acts as State Machine
gem 'argon2' # More secure password hashing than default bcrypt
gem 'bootstrap_form'
gem 'devise' # Authentication
gem 'devise_invitable'
gem 'fast_blank' # Much faster version of #blank?
gem 'friendly_id', github: 'norman/friendly_id' # "friendly" urls like /projects/cool-project
gem 'jsonb_accessor', github: 'volkanunsal/jsonb_accessor' # Store arbitrary model data in jsonb fields
gem 'logidze' # version tracking
gem 'lograge' # one-line logs
gem 'memery' # Memoization
gem 'money-rails'
gem 'nilify_blanks', github: 'swrobel/nilify_blanks'
gem 'oj' # Faster json parsing/generation library
gem 'pg', '>= 0.18', '< 2.0'
gem 'pretender' # Impersonate users
gem 'puma'
gem 'react-rails'
gem 'route_downcaser' # Make routes case-insensitive
gem 'safely' # Move on from exceptions w/ silent reporting to tracking service
gem 'slim-rails' # Template language, lightweight alternative to erb/haml
gem 'stripe'
gem 'strong_migrations' # complains about migration worst-practices
gem 'turbolinks', '~> 5'
gem 'webpacker', github: 'swrobel/webpacker'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pgreset' # Automatically disconnect active pg clients when dropping database
  gem 'referral', require: false # Finds definitions & references in Ruby
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'slim_lint', require: false
end

group :development do
  gem 'awesome_print'
  gem 'brakeman' # Security audits
  gem 'bullet' # Notify of N+1s
  gem 'gindex' # rails g index <table> <column(s)>
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'guard-shell', require: false
  gem 'guard-slimlint', github: 'swrobel/guard-slimlint', require: false
  gem 'invoker', github: 'swrobel/invoker'
  install_if -> { RUBY_PLATFORM =~ /linux/ } do
    gem 'libnotify' # System notifications for Linux
  end
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'partially_useful' # Add html comments around partials
  gem 'rack-toolbar', github: 'swrobel/rack-toolbar', branch: 'only-error-pages' # Insert arbitrary code into Rails error pages
  install_if -> { RUBY_PLATFORM =~ /darwin/ } do
    gem 'terminal-notifier' # System notifications for Mac
    gem 'terminal-notifier-guard'
  end
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console'
end

group :test do
  gem 'rspec-instafail', require: false
  gem 'shoulda-matchers'
end

group :production do
  gem 'actionpack-cloudflare' # Correct request.ip for Cloudflare-proxied requests
  gem 'sentry-raven' # Exception tracking
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
