source "https://rubygems.org"

ruby "~> #{File.read(".ruby-version").strip}"

gem "rails", "~> 6.1.3"

gem "aasm" # Acts as State Machine
gem "active_model_serializers", "~> 0.10.0" # JSON serializer for activerecord
gem "after_commit_everywhere", "~> 1.0" # AASM dependency when using w/ Rails
gem "argon2" # More secure password hashing than default bcrypt
gem "bootstrap-email", github: "swrobel/bootstrap-email", branch: "align-utilities"
gem "bootstrap_form"
gem "bugsnag" # Exception tracking
gem "business", "~> 1.18.0" # Business day calculations. US ACH calendar valid until EOY 2023
gem "devise" # Authentication
gem "devise_invitable"
gem "double_entry", github: "swrobel/double_entry"
gem "email_reply_parser"
gem "errbase" # Generic exception reporting service interface
gem "fast_blank" # Much faster version of #blank?
gem "friendly_id", github: "swrobel/friendly_id", branch: "non-distinct-history" # "friendly" urls like /projects/cool-project
gem "goldiloader" # Automatic eager-loading to avoid N+1s
gem "intercom", "~> 3.9.5"
gem "intercom-rails" # TODO: Remove as this gem has perf issues
gem "jose" # JSON Object Signing & Encryption, required to validate Plaid webhooks
gem "jsonb_accessor" # Store arbitrary model data in jsonb fields
gem "jwt" # Required to validate Plaid webhooks
gem "logidze" # version tracking
gem "lograge" # one-line logs
gem "memery" # Memoization
gem "money-rails"
gem "more_possessive" # Call .possessive on a string
gem "nilify_blanks", github: "swrobel/nilify_blanks"
gem "oj" # Faster json parsing/generation library
gem "pg", ">= 0.18", "< 2.0"
gem "pg_search" # Postgres full-text search support
gem "plaid", "~> 12.0" # Easy bank account linking
gem "pretender" # Impersonate users
gem "puma"
gem "que", "~> 1.0.0.beta4" # Background job processor
gem "que-web", github: "statianzo/que-web"
gem "react-rails"
gem "redcarpet" # Markdown parser
gem "route_downcaser" # Make routes case-insensitive
gem "safely_block" # Move on from exceptions w/ silent reporting to tracking service
gem "sassc-rails"
gem "slim-rails" # Template language, lightweight alternative to erb/haml
gem "sprockets", "< 4.0", require: false
gem "stripe"
gem "strong_migrations" # complains about migration worst-practices
gem "symbol-fstring", "1.0.0", require: "fstring/all" # Improve performance of Symbol#to_s
gem "trestle"
gem "trestle-search"
gem "turbolinks", "~> 5.2"
gem "webpacker"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "fabrication" # Fabricators for models
  gem "faker" # Fake data generation
  gem "pgreset" # Automatically disconnect active pg clients when dropping database
  gem "referral", require: false # Finds definitions & references in Ruby
  gem "rspec-rails"
end

group :development do
  gem "awesome_print"
  gem "brakeman" # Security audits
  gem "gindex" # rails g index <table> <column(s)>
  gem "guard"
  gem "guard-rspec", require: false
  gem "guard-rubocop", github: "swrobel/guard-rubocop", require: false
  gem "guard-shell", require: false
  gem "guard-slimlint", require: false
  gem "invoker"
  install_if -> { RUBY_PLATFORM =~ /linux/ } do
    gem "libnotify" # System notifications for Linux
  end
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "partially_useful" # Add html comments around partials
  gem "rack-toolbar", github: "swrobel/rack-toolbar", branch: "rails-pages" # Insert arbitrary code into Rails pages
  install_if -> { RUBY_PLATFORM =~ /darwin/ } do
    gem "terminal-notifier" # System notifications for Mac
    gem "terminal-notifier-guard"
  end
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "codecov", require: false
  gem "colorize" # Easily colorize text output in the console
  gem "rails-controller-testing" # Allows using assigns() to get controller instance variables in tests
  gem "require_all" # Easily require entire directories
  gem "rspec-instafail", require: false
  gem "rspec_junit_formatter" # For CircleCI enhanced test output
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "stripe-ruby-mock", require: "stripe_mock", github: "swrobel/stripe-ruby-mock"
  gem "webdrivers"
end

group :production, :staging do
  gem "actionpack-cloudflare" # Correct request.ip for Cloudflare-proxied requests
  gem "aws-sdk-s3", require: false
  gem "newrelic_rpm"
  gem "norobots" # Serve up Disallow everything when BLOCK_ROBOTS env var set
  gem "rack-brotli" # Compress responses w/ brotli (better than gzip)
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

eval_gemfile ".overcommit_gems.rb"
