require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Lint/ConstantDefinitionInBlock:
  Exclude:
    - app/models/concerns/**/*

Lint/Debugger:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/OrAssignmentToConstant:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - spec/**/*

Lint/UselessAssignment:
  Exclude:
    - db/seeds/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - '**/*file'
    - '**/*.rake'
    - spec/**/*
    - lib/data_integration/capta/import.rb
    - app/admin/**/*
  AllowedMethods:
    [
      'aasm',
      'context',
      'describe',
      'included',
      'it',
      'DoubleEntry.lock_accounts',
      'transaction',
    ]

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/*file'

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/BulkChangeTable:
  Exclude:
    - db/**/*

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/*pghero*
    - db/migrate/*hierarchies*

Rails/DynamicFindBy:
  Whitelist:
    - find_by_invitation_token
    - find_by_email
  Exclude:
    - spec/system/**/*

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/helpers/devise_bootstrap_helper.rb

Rails/SkipsModelValidations:
  Exclude:
    - db/**/*

Rails/SquishedSQLHeredocs:
  Exclude:
    - db/**/*

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/Focus:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false # Not working w/ system specs

RSpec/SubjectStub:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: false # Stylistic choice, no perf difference: https://github.com/rubocop-hq/rubocop/issues/8247#issuecomment-662269071

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - db/seeds/**/*

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
