exclude:
  - app/views/application/styleguide.slim
  - app/views/layouts/mailer.slim
  - bin/**/*
  - node_modules/**/*
  - tmp/**/*
  - vendor/**/*
linters:
  LineLength:
    enabled: false
  TrailingWhitespace:
    enabled: false
